import { Router } from "express";
import UserController from "../controllers/userController.js";
import AuthMiddleware from "../middleware/AuthMiddleware.js";
import { validate } from "../validators/validate.js";
import { updateUserSchema } from "../validators/userValidator.js";
const router = Router();
router.get("/me", AuthMiddleware.verifyToken, UserController.getUser);
router.put("/me", AuthMiddleware.verifyToken, validate(updateUserSchema), UserController.updateUser);
router.delete("/me", AuthMiddleware.verifyToken, UserController.deleteUser);
export default router;
